In [1]:
import csv
import sqlite3

In [2]:
db_file = 'coalitions.db'

years = ["1994", "1998", "2002", "2006", "2010", "2012", "2016", "2020", "2023"]

conn = sqlite3.connect(db_file)
cur = conn.cursor()
        
for year in years:
    cur.execute(f'''CREATE TABLE IF NOT EXISTS tab{year} (
                iteration_number INTEGER,
                party_number INTEGER,
                samples INTEGER,
                diff INTEGER
                );''')

    # Read and insert data from CSV
    with open(f'./raw_data/1m-{year}coal.csv', 'r') as file:
        reader = csv.reader(file)
        next(reader)  # Skip header if exists
        for i, row in enumerate(reader):
            cur.execute(f'''INSERT INTO tab{year} (iteration_number, party_number, samples, diff)
                            VALUES (?, ?, ?, ?);''', row)
        
# Commit changes and close connection
conn.commit()
conn.close()

In [3]:
# # 2023
# with sqlite3.connect('raw_data.db') as conn:
#     cur = conn.cursor()
#     cur.execute('''DELETE FROM tab2023 WHERE party_number IN (1, 2, 4, 6, 7, 8, 9, 10, 11, 13, 14, 19, 20, 21, 22, 24);''')
#     conn.commit()
# # 2020
# with sqlite3.connect('raw_data.db') as conn:
#     cur = conn.cursor()
#     cur.execute('''DELETE FROM tab2020 WHERE party_number IN (1, 5, 7, 8, 10, 13, 14, 16, 17, 18, 20, 21, 23, 25);''')
#     conn.commit()
# # 2016
# with sqlite3.connect('raw_data.db') as conn:
#     cur = conn.cursor()
#     cur.execute('''DELETE FROM tab2016 WHERE party_number IN (1, 2, 4, 5, 7, 8, 9, 10, 13, 14, 15, 18, 22);''')
#     conn.commit()
# # 2012
# with sqlite3.connect('raw_data.db') as conn:
#     cur = conn.cursor()
#     cur.execute('''DELETE FROM tab2012 WHERE party_number IN (1, 3, 7, 8, 9, 10, 12, 13, 14, 15, 17, 18, 19, 20, 21, 23, 25, 26);''')
#     conn.commit()
# # 2010
# with sqlite3.connect('raw_data.db') as conn:
#     cur = conn.cursor()
#     cur.execute('''DELETE FROM tab2010 WHERE party_number IN (1, 2, 3, 4, 6, 9, 11, 12, 14, 16);''')
#     conn.commit()
# # 2006
# with sqlite3.connect('raw_data.db') as conn:
#     cur = conn.cursor()
#     cur.execute('''DELETE FROM tab2006 WHERE party_number IN (1, 2, 3, 4, 5, 7, 8, 9, 12, 13, 15, 17, 21);''')
#     conn.commit()
# # 2002
# with sqlite3.connect('raw_data.db') as conn:
#     cur = conn.cursor()
#     cur.execute('''DELETE FROM tab2002 WHERE party_number IN (1, 3, 4, 7, 9, 14, 15, 16, 18, 19, 20, 21, 22, 24, 25);''')
#     conn.commit()
# # 1998
# with sqlite3.connect('raw_data.db') as conn:
#     cur = conn.cursor()
#     cur.execute('''DELETE FROM tab1998 WHERE party_number IN (2, 3, 5, 6, 10, 11, 12, 14, 15, 16, 17);''')
#     conn.commit()
# # 1994
# with sqlite3.connect('raw_data.db') as conn:
#     cur = conn.cursor()
#     cur.execute('''DELETE FROM tab1994 WHERE party_number IN (1, 2, 7, 8, 11, 12, 13, 17, 18);''')
#     conn.commit()

In [4]:
# # years = ["2023", "2020", "2016", "2012", "2010", "2006", "2002", "1998", "1994"]
# years = ["1998", "1994"]

# for year in years:
#     with sqlite3.connect('raw_data.db') as conn:
#             cur = conn.cursor()

#             cur.execute(f'''
#                 SELECT iteration_number, party_number, MIN(samples) 
#                 FROM tab{year} 
#                 WHERE diff > 0 
#                 GROUP BY iteration_number, party_number;
#             ''')

#             results = cur.fetchall()

#             with open(f'lowest_samples{year}all.csv', 'w', newline='') as csvfile:
#                 csvwriter = csv.writer(csvfile)
#                 csvwriter.writerow(['iteration_number', 'party_number', 'lowest_samples'])
#                 csvwriter.writerows(results)

In [5]:
# with sqlite3.connect('raw_data.db') as conn:
#         cur = conn.cursor()

#         # Select the lowest samples for each combination of iteration_number and party_number
#         cur.execute('''
#             SELECT iteration_number, party_number, MIN(samples) 
#             FROM tab1m 
#             WHERE diff > 0 
#             GROUP BY iteration_number, party_number;
#         ''')

#         # Fetch the results
#         results = cur.fetchall()

#         # Write results to a CSV file
#         with open('lowest_samples.csv', 'w', newline='') as csvfile:
#             csvwriter = csv.writer(csvfile)
#             csvwriter.writerow(['iteration_number', 'party_number', 'lowest_samples'])  # Write header
#             csvwriter.writerows(results)

#         print("Results exported to lowest_samples.csv")
# year = 2020
# subjects = set(x if x not in (1, 5, 7, 8, 10, 13, 14, 16, 17, 18, 20, 21, 23, 25) else 12 for x in range(1, 26))


# for subject in subjects:
#     with sqlite3.connect('first_change.db') as conn:
#             cur = conn.cursor()

#             cur.execute(f'''
#                 SELECT iteration_number, party_number, MIN(samples) 
#                 FROM tab{year} 
#                 WHERE diff > 0 AND party_number = {subject}
#                 GROUP BY iteration_number, party_number;
#             ''')

#             results = cur.fetchall()

#             with open(f'lowest_samples{year}-p{subject}.csv', 'w', newline='') as csvfile:
#                 csvwriter = csv.writer(csvfile)
#                 csvwriter.writerow(['iteration_number', 'party_number', 'lowest_samples'])
#                 csvwriter.writerows(results)